<template>
  <section class="notfound-wrap">
    <div class="notfound-card">
      <!-- Generated by AI -->
      <div class="qr-wrapper">
        <div class="qr-base"></div>
        <div class="qr-glitch qr-glitch-one"></div>
        <div class="qr-glitch qr-glitch-two"></div>
        <div class="qr-number">404</div>
      </div>
      <!-- End of generated content -->

      <div class="text-center space-y-3 mt-8">
        <p class="text-3xl font-bold text-white drop-shadow leading-snug">Ups, tento stôl sme ešte nezadali</p>
        <p class="text-sm text-white/70">Chceli ste si práve objednať?</p>
      </div>

      <div class="actions">
        <BaseButton class="btn-wrapper max-w-40" @click="$router.push('/')">Späť k menu</BaseButton>
        <BaseButton class="btn-wrapper max-w-40" variant="secondary" @click="$router.push('/kontakt')">
          Kontaktovať obsluhu
        </BaseButton>
      </div>

      <p class="mt-6 text-white/60 text-center text-sm">
        Chceli ste práve objednať? Stránka sa stratila rýchlejšie než obsluha v piatok večer.
      </p>
    </div>
  </section>
</template>

<script>
import BaseButton from '@/components/global/buttons/BaseButton.vue';

export default {
  name: 'NotFoundView',
  components: { BaseButton },
};
</script>

<style scoped>
/* Generated by AI */
.notfound-wrap {
  min-height: calc(100vh - 180px);
  background: radial-gradient(circle at top, rgba(23, 41, 64, 0.95), rgba(9, 16, 24, 0.98));
  filter: drop-shadow(0 10px 20px rgba(0, 0, 0, 0.35));
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 3rem 1.5rem;
}

.notfound-card {
  background: rgba(17, 26, 35, 0.85);
  border: 1px solid rgba(255, 255, 255, 0.1);
  border-radius: 28px;
  padding: 3rem 2rem;
  max-width: 640px;
  width: 100%;
  position: relative;
  overflow: hidden;
  text-align: center;
}

.qr-wrapper {
  position: relative;
  width: 220px;
  height: 220px;
  margin: 0 auto;
}

.qr-base {
  width: 100%;
  height: 100%;
  background: repeating-linear-gradient(
      90deg,
      rgba(255, 255, 255, 0.12) 0,
      rgba(255, 255, 255, 0.12) 8px,
      transparent 8px,
      transparent 16px
    ),
    repeating-linear-gradient(
      0deg,
      rgba(255, 255, 255, 0.12) 0,
      rgba(255, 255, 255, 0.12) 8px,
      transparent 8px,
      transparent 16px
    );
  border-radius: 24px;
  border: 2px solid rgba(255, 255, 255, 0.15);
}

.qr-glitch {
  position: absolute;
  inset: 0;
  border-radius: 24px;
  mix-blend-mode: screen;
  animation: glitch 3s infinite ease-in-out;
}

.qr-glitch-one {
  background: repeating-linear-gradient(
    90deg,
    rgba(12, 202, 186, 0.4) 0,
    rgba(12, 202, 186, 0.4) 6px,
    transparent 6px,
    transparent 16px
  );
}

.qr-glitch-two {
  background: repeating-linear-gradient(
    0deg,
    rgba(59, 130, 246, 0.4) 0,
    rgba(59, 130, 246, 0.4) 6px,
    transparent 6px,
    transparent 16px
  );
  animation-delay: 0.6s;
}

.qr-number {
  position: absolute;
  inset: 0;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 4rem;
  font-weight: 800;
  color: rgba(255, 255, 255, 0.3);
}

@keyframes glitch {
  0% {
    transform: translate(0);
  }
  25% {
    transform: translate(-6px, 4px) skew(0.6deg);
  }
  50% {
    transform: translate(4px, -2px) skew(-0.5deg);
  }
  75% {
    transform: translate(-3px, 3px);
  }
  100% {
    transform: translate(0);
  }
}

/*end of generated content*/

.actions {
  display: flex;
  gap: 1rem;
  justify-content: center;
  flex-wrap: wrap;
  align-content: center;
  margin-top: 1.5rem;
}

.btn-wrapper {
  display: flex;
  justify-content: center;
  text-transform: uppercase;
  letter-spacing: 0.08em;
}

@media (max-width: 640px) {
  .notfound-card {
    padding: 2rem 1.25rem;
  }
  .qr-wrapper {
    width: 170px;
    height: 170px;
  }
  .actions {
    flex-direction: column;
  }
}
</style>
