<template>
  <BaseModal v-model="proxyVisible" :title="modalTitle" class="max-h-[90vh]">
    <div class="flex flex-wrap gap-2 pb-4">
      <button
        v-for="tab in tabs"
        :key="tab.key"
        class="rounded-full px-4 py-1.5 text-sm font-semibold transition cursor-pointer"
        :class="tabClass(tab.key)"
        @click="activeTab = tab.key"
      >
        {{ tab.label }}
      </button>
    </div>

    <div v-if="activeTab === 'basic'" class="space-y-2">
      <div class="grid gap-2 md:grid-cols-2">
        <BaseInput label="Názov jedla" v-model="form.name" required />
        <BaseSelect
          label="Kategória"
          :options="categoryOptions"
          option-label-key="label"
          option-value-key="key"
          v-model="form.categoryKey"
          placeholder="Vyberte kategóriu"
          required
        />
      </div>

      <BaseTextarea label="Popis" v-model="form.description" rows="4" />

      <div class="grid gap-2 md:grid-cols-2">
        <BaseInput label="Čas prípravy" v-model="form.preparationTime" placeholder="15-20 min" />
        <BaseInput label="Alergény" v-model="form.allergens" placeholder="Laktóza, Lepok…" />
      </div>

      <BaseUpload label="Nahrať obrázok" v-model="form.imageFile" placeholder="Vyberte obrázok" accept="image/*" />

      <img
        v-if="imagePreview"
        :src="imagePreview"
        alt="Náhľad jedla"
        class="w-full rounded-2xl object-cover h-48 border border-ink/10"
      />

      <BaseCard class="space-y-6">
        <p class="font-semibold text-deep">Dostupnosť</p>
        <div class="flex flex-col gap-4">
          <BaseToggle
            v-model="form.visibleInMenu"
            label="Viditeľné v menu"
            class="flex flex-row-reverse w-full justify-between"
          />
        </div>
      </BaseCard>
    </div>
    <div v-else class="text-sm text-ink/70">Táto sekcia bude dostupná čoskoro.</div>

    <template #footer>
      <div class="flex justify-end gap-3">
        <BaseButton variant="secondary" @click="handleCancel">Zrušiť</BaseButton>
        <BaseButton @click="handleSubmit">{{ mode === 'edit' ? 'Uložiť zmeny' : 'Pridať jedlo' }}</BaseButton>
      </div>
    </template>
  </BaseModal>
</template>

<script>
//generated by ai
import BaseModal from '@/components/global/containers/BaseModal.vue';
import BaseInput from '@/components/global/inputs/BaseInput.vue';
import BaseTextarea from '@/components/global/inputs/BaseTextarea.vue';
import BaseSelect from '@/components/global/inputs/BaseSelect.vue';
import BaseToggle from '@/components/global/inputs/BaseToggle.vue';
import BaseCard from '@/components/global/containers/BaseCard.vue';
import BaseButton from '@/components/global/buttons/BaseButton.vue';
import BaseUpload from '@/components/global/inputs/BaseUpload.vue';
import { CATEGORY_ICON_OPTIONS } from '@/constants/categoryIcons';

export default {
  name: 'MenuItemModal',
  components: { BaseModal, BaseInput, BaseTextarea, BaseSelect, BaseToggle, BaseCard, BaseButton, BaseUpload },
  props: {
    modelValue: {
      type: Boolean,
      default: false,
    },
    mode: {
      type: String,
      default: 'create',
    },
    item: {
      type: Object,
      default: null,
    },
  },
  emits: ['update:modelValue', 'save'],
  data() {
    return {
      form: {
        name: '',
        categoryKey: '',
        description: '',
        preparationTime: '',
        allergens: '',
        imageUrl: '',
        imageFile: null,
        visibleInMenu: true,
        availableForDelivery: true,
        onSiteOnly: false,
      },
      activeTab: 'basic',
      previewUrl: '',
      objectUrl: null,
      tabs: [
        { key: 'basic', label: 'Základné' },
        { key: 'variants', label: 'Varianty' },
        { key: 'addons', label: 'Prídavky' },
      ],
    };
  },
  computed: {
    proxyVisible: {
      get() {
        return this.modelValue;
      },
      set(value) {
        this.$emit('update:modelValue', value);
      },
    },
    modalTitle() {
      return this.mode === 'edit' ? 'Upraviť jedlo' : 'Pridať nové jedlo';
    },
    categoryOptions() {
      return CATEGORY_ICON_OPTIONS.map((option) => ({
        key: option.key,
        label: option.label,
      }));
    },
    imagePreview() {
      return this.previewUrl || this.form.imageUrl;
    },
  },
  watch: {
    modelValue(value) {
      if (value) {
        this.syncForm();
      }
    },
    item: {
      deep: true,
      handler() {
        if (this.modelValue) {
          this.syncForm();
        }
      },
    },
    'form.imageFile'(file) {
      this.setPreviewFromFile(file);
    },
  },
  methods: {
    tabClass(key) {
      if (this.activeTab === key) {
        return 'bg-primary/10 text-primary border border-primary/30';
      }
      return ' text-deep hover:bg-ink/50 disabled:opacity-60 disabled:cursor-not-allowed';
    },
    syncForm() {
      const source = this.item || {};
      this.form = {
        name: source.name || '',
        categoryKey: source.categoryKey || '',
        description: source.description || '',
        preparationTime: source.preparationTime || '',
        allergens: source.allergens || '',
        imageUrl: source.imageUrl || source.image || '',
        imageFile: null,
        visibleInMenu: source.visibleInMenu !== undefined ? source.visibleInMenu : true,
        availableForDelivery: source.availableForDelivery !== undefined ? source.availableForDelivery : true,
        onSiteOnly: source.onSiteOnly || false,
      };
      this.clearPreviewUrl();
      this.previewUrl = this.form.imageUrl || '';
      this.activeTab = 'basic';
    },
    handleCancel() {
      this.proxyVisible = false;
    },
    handleSubmit() {
      this.$emit('save', { ...this.form, mode: this.mode });
      this.proxyVisible = false;
    },
    setPreviewFromFile(file) {
      this.clearPreviewUrl();
      if (file instanceof File) {
        this.objectUrl = URL.createObjectURL(file);
        this.previewUrl = this.objectUrl;
      } else if (typeof file === 'string') {
        this.previewUrl = file;
      } else if (this.form.imageUrl) {
        this.previewUrl = this.form.imageUrl;
      } else {
        this.previewUrl = '';
      }
    },
    clearPreviewUrl() {
      if (this.objectUrl) {
        URL.revokeObjectURL(this.objectUrl);
        this.objectUrl = null;
      }
    },
  },
  beforeUnmount() {
    this.clearPreviewUrl();
  },
};
</script>
