// generated by AI

export function formatCurrency(value, locale = 'sk-SK', currency = 'EUR') {
  if (value === null || value === undefined || Number.isNaN(Number(value))) {
    return '';
  }
  return new Intl.NumberFormat(locale, {
    style: 'currency',
    currency,
  }).format(value);
}
